### PR TITLE
data: Add support for the HP Pro Tablet 408

### PR DESCRIPTION
**Pull request by ShapeShifter499**
Link: https://github.com/linuxwacom/wacom-hid-descriptors/issues/137

### CODE REVIEW

**Comment by ShapeShifter499** [comment]
This tablet seems to be typically held in portrait mode, vertically. When my ruler is laid onto the tablet, I measure 4 1/4th inches by 7 3/4th inches or 108mm by 172mm.  So I rounded to 4 inches by 7 inches, I hope that was correct.

**Comment by ShapeShifter499** [comment]
Added note to the tablet file that specifies that this uses a HP branded stylus.

**Review by whot — APPROVED** [review]
thanks

**Comment by ShapeShifter499** [comment]
@whot I don't know what happened but the change I made to the file didn't get picked up by github

```               
# This is for the HP Pro Tablet 408
#
# Synaptics I2C sensor
# Makes use of a HP branded sylus
#
# https://github.com/linuxwacom/wacom-hid-descriptors/issues/137

[Device]
Name=HP Pro Tablet 408
Class=ISDV4
DeviceMatch=i2c:06cb:125d
Width=4
Height=7
IntegratedIn=Display;System;

[Features]
Stylus=true
Touch=true
Buttons=0
```

**Comment by ShapeShifter499** [comment]
Ok I screwed up and I didn't properly push the file to my repository. In any case I just was trying to add ```# Makes use of a HP branded stylus``` to the file

**Comment by whot** [comment]
easiest to just file a new MR with that one line added. tablet files can be changed after they're merged :)

**Comment by ShapeShifter499** [comment]
@whot  did I do this correctly? https://github.com/linuxwacom/libwacom/pull/354

**Comment by ShapeShifter499** [comment]
I think I screwed it up, I forced pushed onto branch in my fork after you merged this PR

**Comment by whot** [comment]
I can squash it - next time just do this (while on your branch)
```
$ git rebase origin/master
# fix any conflicts, then run git add and git rebase --continue
$ git push -f <remote> <branch>
```
Or create a new branch so you don't need to force-push

**Comment by ShapeShifter499** [comment]
Thank you. I'll keep that in mind next for time

**Pull request merged**
