### PR TITLE
Add Wacom HID 52D3 (Lenovo Yoga 7 14ARB7)

### PR DESCRIPTION
**Pull request by imsofi**

### CODE REVIEW

**Comment by imsofi** [comment]
Would like feedback if this should have been merged with #549 or be separate like this. The 14ARB7 Yoga model ships with 2 different screen setups, so i think they are distinct even if under the same model name of laptops.

**Comment by imsofi** [comment]
Also are there any ways to stop the screen announcing it has a battery? It shows up even when configured to have a battery of 0%

image

**Comment by imsofi** [comment]
Seems related to upower misrepresenting the digitizer "missing" battery as a battery with 0% power.

https://gitlab.freedesktop.org/upower/upower/-/issues/221

https://gitlab.freedesktop.org/upower/upower/-/issues/197

**Comment by imsofi** [comment]
So it's announced correctly, but I am struggling making the pen work. Doing a `libinput debug-events` ends up not showing any events from using the pen or any of its buttons. This is likely something i missed on my end, but i am not entirely sure where to look to find out why the pen is not showing up.

```
% sudo libinput debug-events
-event0   DEVICE_ADDED            Video Bus                         seat0 default group1  cap:k
-event3   DEVICE_ADDED            Power Button                      seat0 default group2  cap:k
-event2   DEVICE_ADDED            Lid Switch                        seat0 default group3  cap:S
-event15  DEVICE_ADDED            HD-Audio Generic Headphone        seat0 default group4  cap:k
-event7   DEVICE_ADDED            Integrated RGB Camera: Integrat   seat0 default group5  cap:k
-event11  DEVICE_ADDED            Integrated RGB Camera: Integrat   seat0 default group5  cap:k
-event4   DEVICE_ADDED            Ideapad extra buttons             seat0 default group6  cap:k
-event9   DEVICE_ADDED            MSFT0001:00 06CB:CE44 Mouse       seat0 default group7  cap:p left scroll-nat scroll-button
-event13  DEVICE_ADDED            MSFT0001:00 06CB:CE44 Touchpad    seat0 default group7  cap:pg  size 117x72mm tap(dl off) left scroll-nat scroll-2fg-edge click-buttonareas-clickfinger dwt-on dwtp-on
-event16  DEVICE_ADDED            Wacom HID 52D3 Pen                seat0 default group8  cap:T  size 302x189mm calib
-event17  DEVICE_ADDED            Wacom HID 52D3 Finger             seat0 default group8  cap:t  size 302x189mm ntouches 10 calib
-event5   DEVICE_ADDED            Lenovo Yoga Mode Control switch   seat0 default group9  cap:S
-event1   DEVICE_ADDED            AT Translated Set 2 keyboard      seat0 default group10 cap:k
 event1   KEYBOARD_KEY            +4294967.295s	*** (-1) pressed
 event1   KEYBOARD_KEY            +0.101s	*** (-1) released
 event1   KEYBOARD_KEY            +0.439s	*** (-1) pressed
 event1   KEYBOARD_KEY            +0.522s	*** (-1) released
 event1   KEYBOARD_KEY            +11.951s	*** (-1) pressed
 event1   KEYBOARD_KEY            +12.064s	*** (-1) released
 event1   KEYBOARD_KEY            +12.795s	*** (-1) pressed
 event1   KEYBOARD_KEY            +12.978s	*** (-1) pressed
 ```

**Comment by imsofi** [comment]
It is a Lenovo E-Color Pen if that can help.

**Comment by whot** [comment]
> The 14ARB7 Yoga model ships with 2 different screen setups, so i think they are distinct even if under the same model name of laptops.

Let's keep it separate unless we're sure it's the exact same device but with different PIDs. It doesn't matter much anyway,  libwacom is just a database.

> Also are there any ways to stop the screen announcing it has a battery? 

Not in libwacom - this library is just a C wrapper around a text-based database. But you already found the upower bugs, so I don't have anything to add to that.


> Doing a libinput debug-events ends up not showing any events from using the pen or any of its buttons. This is likely something i missed on my end, but i am not entirely sure where to look to find out why the pen is not showing up.

Check with `libinput record`, that records kernel events. If that doesn't show anything, the required kernel support is missing and userspace can't do anything about that. if it *does* show something, please attach the recording to a new libinput issues and we can look at it from there.

For the kernel support, the `hid-recorder` output will help tell us what the device actually sends over the wire.


Meanwhile - this MR for libwacom looks good, merging. Thanks!

**Comment by imsofi** [comment]
> but I am struggling making the pen work.

Okay so I think must be my greatest oops of the year so far. The pen had ran out of battery, and i did not realize it needed to charge in order for it to function. :facepalm: 

Everything works amazing now. Thank you @whot!

**Pull request merged**
