### PR TITLE
elan-264c: add styli detection

### PR DESCRIPTION
**Pull request by luyatshimbalanga**

### CODE REVIEW

**Comment by whot** [comment]
This seems to conflict with the file from #55, is that new file needed?

**Comment by luyatshimbalanga** [comment]
Not needed. The file is simply an update and I don't know why github called it few.

**Comment by whot** [comment]
github says about your master branch:

>  This branch is 5 commits ahead, 110 commits behind linuxwacom:master. 

you just need to do a `git pull --rebase` first. And can you squash the commits together please so there aren't 5 of them? Thanks.

**Comment by luyatshimbalanga** [comment]
Done.

**Comment by whot** [comment]
rebase please, not a merge

**Comment by luyatshimbalanga** [comment]
I deleled my old fork as it got messed up and recreate a [new one with rebase](https://github.com/luyatshimbalanga/libwacom/commit/f1b0cc7336a6a128fe7aa4eadc3c5987ed6449df). Should I open a new pull request instead>\?

**Comment by whot** [comment]
you can just force-push to the original branch name here - `git push -f $remotename $branchname`, replacing the two for whatever you called the remote and branch. That'll show up in the PR and drop the previous bits - that's the easiest way and much less invasive than wiping everything.

But yes, please open a new PR then, thanks. Closing this one.

**Pull request closed without merging**
