### PR TITLE
data: Add Intuos Pro 5 M wireless

### PR DESCRIPTION
**Pull request by battlesnake**
Duplicated Intuos Pro M profile to new profile and set ID for when used wirelessly.

### CODE REVIEW

**Comment by skomra** [comment]
0x84 is the PID of the dongle, which I think works with another device as well. I did a quick test on Ubuntu 18.04 and I was able to map the buttons for this device used over wireless. So I think this device is already supported.

**Comment by whot** [comment]
ah, cool, thanks. do we have a list of dongles? would make sense to put in a CI check for the dongle IDs so we prevent any inadvertent merges?

**Comment by Pinglinux** [comment]
As far as I know, there is only wireless dongle, which is 0x84.

**Comment by whot** [comment]
Receiver check was added in #199

**Comment by whot** [comment]
I'm closing this, based on https://github.com/linuxwacom/libwacom/pull/197#issuecomment-573764511 and the fact that this one adds the dongle, not the actual device. Thanks though.

**Pull request closed without merging**
