### PR TITLE
data: set the right PID for the Inpspiroy 2 L and M

### PR DESCRIPTION
**Pull request by whot**
See https://github.com/DIGImend/digimend-kernel-drivers/pull/679

### CODE REVIEW

**Review by JoseExposito — APPROVED** [review]
You were faster than me :wink: . It'd be nice if @tequeter could test this and add the missing information (sysinfo, width and height).

**Comment by whot** [comment]
going to merge this while I'm yak shaving and it should hopefully work anyway. thanks for the quick review, @tequeter - filling in the missing pieces of the `.tablet` file (and ideally the SVG too) would be very much appreciated.

**Comment by tequeter** [comment]
I've started working on it.

**Comment by whot** [comment]
ftr, I fixed the svg files in #696 though admittedly this is the bare minimum and if you want to make them prettier/more accurate/etc. that'd be very welcome.

**Pull request merged**
