### PR TITLE
test: add some tracing to the svg validity test

### PR DESCRIPTION
**Pull request by whot**
It's a bit hard to figure out from the CI logs what failed because they may be truncated. And for users not intimitely familiar with the test suite it's not that simple either so let's put in a bunch of trace stataments that should at least point to where things go wrong.

cc @AesaraB

### CODE REVIEW

**Comment by AesaraB** [comment]
Mildly tangential, but I made a fairly rudimentary bash script to debug things.

```bash
#!/usr/bin/env bash

FILENAME=$1

echo "Checking for invalid class/id names"
grep -P "(class|id)=[\"'].*[\"']" $FILENAME | grep -vP '(class="[A-Z] (Button|Leader|Label)|id="(Button|Leader|Label)[A-Z])"'

echo "Checking for duplicate ids"
grep -P "id=[\"'](Button|Leader|Label)[A-Z][\"']" $FILENAME | sort | uniq -cd

echo "Checking for duplicate classes"
grep -P "class=[\"'][A-Z] (Button|Leader|Label)[\"']" $FILENAME | sort | uniq -cd
```

**Comment by whot** [comment]
honestly, I think the whole svg validity test should be rewritten in python + pytest - it'll be simpler and provide better debugging options than the current one (which is now 12y old...)

**Comment by AesaraB** [comment]
> honestly, I think the whole svg validity test should be rewritten in python + pytest - it'll be simpler and provide better debugging options than the current one (which is now 12y old...)

I'm unfamiliar with low level programming, but I just heard some terms and ideas that I'm relatively familiar with.

I have some housekeeping to do with other projects and my personal life, so if I get those sorted before someone else commits their time to this, I think I should be able to write that code.

**Comment by whot** [comment]
heh, I don't think in this case it's really low-level programming - you can parse the data files in python (`ConfigParser` will do it) and then for each svg file check that the expected bits exist.

We already have a python test to check the data files exist (`test_svg_exists()`), it would be a similar test to also check that for each Button `A` we have an svg element with `id="Button A"` that also has `class="A Button"`. Then repeat for rings/strips/etc.

Definitely a good one to get started with, doubly so if you want to learn python :)

**Comment by whot** [comment]
Going to merge this since @JoseExposito also ran into the issue of the svg checks not being particularly useful with their error messages. The output is a bit spammy and I've changed to to stderr now so it doesn't conflict with the TAP output on stdout but it's still better than a comment-less `abort()`

**Comment by whot** [comment]
> honestly, I think the whole svg validity test should be rewritten in python + pytest - it'll be simpler and provide better debugging options than the current one (which is now 12y old...)

This is now part of #677

**Pull request merged**
