### PR TITLE
add support for surface go

### PR DESCRIPTION
**Pull request by idnovic**
this adds support for surface go and the integrated device is displayed inside gnome settings

### CODE REVIEW

**Comment by whot** [comment]
Build error was caused by a meson bug, retriggered CI now

**Comment by whot** [comment]
ok, this time it's a real bug: please add the file to `meson.build`, see previous commits for a guide

**Comment by idnovic** [comment]
okay I will in a few days

**Comment by ShapeShifter499** [comment]
@idnovic Any updates on this?  

@whot should I submit a fix for this?

**Comment by ShapeShifter499** [comment]
I own a Surface Go 1 and would like to see this added for Gnome support.

**Comment by idnovic** [comment]
> @idnovic Any updates on this?  
> 
> 
> 
> @whot should I submit a fix for this?

Yes please submit a fix. 
I do not use linux anymore. 

Thank you!

**Comment by whot** [comment]
@ShapeShifter499 - yes, please submit a new PR for this. The requirement for `meson.build` has since gone away so I **think** the CI will be happy if you rebase this branch on top of current master.

Having said that - please add the sysinfo to https://github.com/linuxwacom/wacom-hid-descriptors and link to it from the `.tablet` file so we can debug this easier in the future (if we need to).

**Comment by whot** [comment]
Closing this based on https://github.com/linuxwacom/libwacom/pull/196#issuecomment-773463316 and with eager anticipation of a new PR :)

**Comment by ShapeShifter499** [comment]
Submitted a new PR :3 

https://github.com/linuxwacom/libwacom/pull/352

**Pull request closed without merging**
