### PR TITLE
data: Add elan-0732 (HP ENVY x360 Convertible 13-ag0xxx)

### PR DESCRIPTION
**Pull request by ColinKinloch**
Seems to work on my envy x360, I just copied elan-262b.tablet and changed the device match.
Is there anything else I need to check?

### CODE REVIEW

**Comment by whot** [comment]
unrelated to the patch here: @jigpu are you seeing travis results in PRs? this is the second one where I noticed nothing shows up.

**Comment by whot** [comment]
fwiw, I tested this locally and the script disagreed about the sorting order. Which caused me to look up meson things again and eventually resulted in #232. Once that's merged you can just drop the second commit here and  we can merge this one.

**Comment by whot** [comment]
rebased locally and test suite succeed, merging. Thanks!

**Comment by PiFern** [comment]
Hi ! I'm not sure if it's the right place to post, please tell me if it's not...
On my computer "HP Pavilion x360 Convertible", tablet and stylus are working (even if the stylus isn't really precise) using the "serial-wacf004.tablet" file, but "xinput --list" returns "ELAN0732:00 04F3:251C" for the device, so "04f3:251c" should be added to "elan-0732.tablet" file ? Is there anything else to do to make my tablet well handled ?
"xsetwacom --list" doesn't return anything, i don't know if it should ...

**Pull request merged**
